### ISSUE TITLE
Toggle Icon static to dynamic setup

### ISSUE THREAD

**Issue by muslimakhan** [ahmedkaludi/Easy-Table-of-Contents#359]
### Description:
Toggle SVG icon is on static at this time so icon should be setup dynamically from admin panel and color also changed & custom upload by users.

#### Tasks:

- [ ] Pre-built icons
- [ ] Icon color change
- [ ] Upload PNG/SVG icon

#### Reference Link:
https://wordpress.org/support/topic/change-toggle-icon-3/

#### Reference Screenshots:
https://prnt.sc/2LCFU00NPvju
