### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/Easy-Table-of-Contents#658]
- [x] Inline all text boxes with same width Ref: https://prnt.sc/Kf0Y-kmi9l8D
- [x] Link is missing https://prnt.sc/hmikzkkUfPJN
- [x] Add sticky inside how to use https://prnt.sc/RioCeg58CAvv
- [x] Describe shortcode parameters https://prnt.sc/yA2wYzQFelQr
- [x] Add newly added hooks here https://prnt.sc/C7iMdMA-4xPb
